### ISSUE TITLE
GetHabboClubCenterInfoMessageEvent missing

### ISSUE THREAD

**Issue by Valaisin** [80O/PlusEMU#145] opened 2022-08-10 16:56 UTC
Communication packet missing because of this the `HC` button on the top right forces you to disconnect. 

Simply click the HC button and it will disconnect from game.

What it needs to do: 
The HC window to open.

Required work: 
- Find ID of GetHabboClubCenterInfoMessageComposer
- Add into JSON 
- Implement the Outgoing packet.

**Comment by 80O** [comment] 2022-08-15 11:15
Duplicate of #142

**Closed by 80O** 2022-08-15 11:15 UTC
Labels: bug
